language: ruby
rvm:
- 1.9.3
script: bundle exec jekyll build
install: bundle install
after_success: bundle exec s3_website push --headless --site public
env:
  global:
  - secure: RjERJuS00UNWv5O9sNu5ZYiEKlS218AJyZOt26wOmbwzr1evERW8q9i1uMDK/OfEf+j1ob3Pm4ged0h5Y39KtM/ytMwFIBafzqcxUkXqJlQtnTWsdr8i/i1OfFJvNNlV1BTU/ZO7ML2caj8Da+na4MjTVg7Blhd5qqasJSR0l1s=
  - secure: WU4bJrKZhwd14Bl2d7uHSxwCOMO7EriUeIcplVXrDU/g/BJY8DEk8PxEy3I5docMWqKO47acObKGrMcswh2yi87erJw26emFkVSNMYsR+lwZWKGizpDLJ/YCwRoywFV6xF0i655DPIroptgnphM4FGQHJZDsNfGky1jx2LtGJgE=
  - secure: QdwCo+WSkQlDPk5U2R3/4v151mOFvOaGu/VdRHJGpAYARdCWxkRMrkg15/ijCNF6V/YqNlGMdacMvylzp3yv8SVjU9/COxzK1Y2E7NJJVE5nWVgVh4kT+LEMethcd/OWONPMjCwgotI3IoynYZ1SWjddS8UPLSKxeSQnvIf8tlc=
  - secure: LqC6K8wG3p2ql73C1EiLUAoTr/oD5nlpqKefl6iqKY39ChL3dVmsKPDdSvnGys/R74eegbz3xS67a/hjP2aQzXSufXG7CQtV33jZzoTWJuddVAf+hedQvi4D/QMLUpY1UFeJMa/e25orLDSJ3XFSPHIKAVcmLEabPoXKTrBHAHI=
  - secure: IX9EPAOL86JpMJ9HnMvGRic9kssUrMzfc9WaHhqshVGxHNjOezrO4aL+SxnAcmiNc6cVbGXak5ZxHK67o9/80nRgyOqFt/oes731rsP2u0PMbj8IX4bw7/EtvEfT/xRwwmDQlHOdd+ITM3BQcUiUrPNszt/CE2/Zqw4M2gZx3J4=
  - secure: ImnHl2U5gPE6ci+J9lvrhCIJ9iNLjSUGdf23RWYdEVSMZpxISohdO+MXEfZJCBcq6DNRjOrlEMxpszqSjq6PeHM9QaqkNACkmXOsru9WE8ZgvZdvngrP23xOHttg+Qy9Z2KQQGt6L4BxYlRn1juJ3Ah5lLItRpGxH3vb0t0KodM=
