name: Kennedia Consulting
markdown: redcarpet
pygments: true
paginate: 5
paginate_path: "news/page:num"
destination: public
exclude: ["README.md", "public", "assets", "Gemfile", "Gemfile.lock", "s3_website.yml"]